# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98fb1626af9460922a67c7b9ca54ea65e4448cfd0f848df4bd531207cd614bfcdbe71e1adde6f2a107a527f9f1be99b94059c60e37025255f025e6c039007aec

test:
  secret_key_base: 80f3fbb4407fe3b440166f62b78b72d9ec2c2e2eb16994467950c50918946c510eaaedf57da3e15fe01f1a8b30d10d37128ecd2a91ad1910e45e627c7c78f5a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
